// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2019-09-23 20:20:42.262277902 -0500 CDT m=+0.000170129
package azure_resources

import (
	"context"

	"github.com/Azure/azure-sdk-for-go/profiles/latest/network/mgmt/network"
	"github.com/Azure/go-autorest/autorest"
)

type NetworkPublicIPAddresses struct {
	subscriptionID string
	groupName      string
	resourceName   *string
	authorizer     autorest.Authorizer
	resource       network.PublicIPAddress
}

func (r *NetworkPublicIPAddresses) GetId() *string {
	return r.resource.ID
}

func (r *NetworkPublicIPAddresses) GetProperties() ([]byte, error) {
	client := network.NewPublicIPAddressesClient(r.subscriptionID)
	client.Authorizer = r.authorizer

	resource, err := client.Get(context.Background(), r.groupName, *r.resourceName, "")
	if err != nil {
		return []byte{}, err
	}

	r.resource = resource

	return resource.MarshalJSON()
}

type NetworkVirtualNetworks struct {
	subscriptionID string
	groupName      string
	resourceName   *string
	authorizer     autorest.Authorizer
	resource       network.VirtualNetwork
}

func (r *NetworkVirtualNetworks) GetId() *string {
	return r.resource.ID
}

func (r *NetworkVirtualNetworks) GetProperties() ([]byte, error) {
	client := network.NewVirtualNetworksClient(r.subscriptionID)
	client.Authorizer = r.authorizer

	resource, err := client.Get(context.Background(), r.groupName, *r.resourceName, "")
	if err != nil {
		return []byte{}, err
	}

	r.resource = resource

	return resource.MarshalJSON()
}
