// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// {{ .Timestamp }}
package azure_resources

import (
	"context"

	"github.com/Azure/azure-sdk-for-go/profiles/latest/{{ ToLower .Type }}/mgmt/{{ ToLower .Type }}"
	"github.com/Azure/go-autorest/autorest"
)

{{ range .Resources }}
type {{ $.Type }}{{ Title . }} struct{
	subscriptionID string
	groupName      string
	resourceName   *string
	authorizer     autorest.Authorizer
	resource       {{ ToLower $.Type }}.{{ CapitalizeAndSingularize . }}
}

func (r *{{ $.Type }}{{ Title . }}) GetId() *string {
	return r.resource.ID
}

func (r *{{ $.Type }}{{ Title . }}) GetProperties() ([]byte, error) {
	client := {{ ToLower $.Type }}.New{{ Title . }}Client(r.subscriptionID)
	client.Authorizer = r.authorizer

	resource, err := client.Get({{ GetParameters . }})
	if err != nil {
		return []byte{}, err
	}

	r.resource = resource

	return resource.MarshalJSON()
}
{{ end }}
